### ISSUE TITLE
Gloves not saving 

### ISSUE THREAD

**Issue by drakin003** [Nereziel/cs2-WeaponPaints#172]
Every time I join the server, gloves gets removed. I am using retakes.

error in logs:
`2024-02-25 08:43:07.375 +08:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadInt64(IntPtr ptr, Int32 ofs)
   at CounterStrikeSharp.API.Core.CBaseEntity.GetVData[T]() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CBaseEntity.cs:line 30
   at WeaponPaints.WeaponPaints.<>c__DisplayClass19_0.<RefreshWeapons>b__1() in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponAction.cs:line 279
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82
`

CSSharp version: v172
Settings:
"Additional": {
    "SkinVisibilityFix": true,
    "KnifeEnabled": true,
    "GloveEnabled": true,
    "SkinEnabled": true,
    "CommandWpEnabled": true,
    "CommandKillEnabled": true,
    "CommandKnife": "knife",
    "CommandGlove": "gloves",
    "CommandSkin": "ws",
    "CommandSkinSelection": "skins",
    "CommandRefresh": "wp",
    "CommandKill": "kill",
    "GiveRandomKnife": false,
    "GiveRandomSkin": false,
    "GiveKnifeAfterRemove": true,
    "ShowSkinImage": false
  },

### Gloves are still not working, even though they are getting stored in the database.
![Capture](https://github.com/Nereziel/cs2-WeaponPaints/assets/23008063/446f4794-65cf-4316-949e-c6341e6b3198)

**Comment by drakin003** [comment]
seems to be fixed in build 224
