### ISSUE TITLE
CSSharp V193 Meta 1284 Error

### ISSUE THREAD

**Issue by t4r1k58** [Nereziel/cs2-WeaponPaints#205]
Loading plugin WeaponPaints
2024-03-09 12:55:51.445 +00:00 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/cs27015/serverfiles/game/csgo/addons/counterstrikesharp/plugins/WeaponPaints/WeaponPaints.dll
System.Text.Json.JsonReaderException: '"' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 20 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkipped(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.Parse(Stream utf8Json, JsonDocumentOptions options)
   at CounterStrikeSharp.API.Core.Translations.JsonResourceManager.LoadJsonResources(String filePath) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonResourceManager.cs:line 145
   at CounterStrikeSharp.API.Core.Translations.JsonResourceManager.TryLoadResourceSet(String cultureName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonResourceManager.cs:line 124
   at CounterStrikeSharp.API.Core.Translations.JsonResourceManager.TryLoadResourceSet(CultureInfo culture) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonResourceManager.cs:line 135
   at CounterStrikeSharp.API.Core.Translations.JsonResourceManager.GetResourceSet(CultureInfo culture, Boolean tryParents) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonResourceManager.cs:line 36
   at CounterStrikeSharp.API.Core.Translations.JsonResourceManager.GetString(String name, CultureInfo culture) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonResourceManager.cs:line 108
   at CounterStrikeSharp.API.Core.Translations.JsonStringLocalizer.GetStringSafely(String name, CultureInfo culture) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonStringLocalizer.cs:line 65
   at CounterStrikeSharp.API.Core.Translations.JsonStringLocalizer.get_Item(String name) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/JsonStringLocalizer.cs:line 34
   at CounterStrikeSharp.API.Core.Translations.StringLocalizer.get_Item(String name) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Translations/StringLocalizer.cs:line 18
   at WeaponPaints.WeaponPaints.SetupKnifeMenu() in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/Commands.cs:line 143
   at WeaponPaints.WeaponPaints.Load(Boolean hotReload) in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponPaints.cs:line 220
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93

**Comment by asdfxD** [comment]
Build 222 no knife is given @linux.

**Comment by Waterovsky** [comment]
**CSS 193, meta 1284, WP 2.2c**
Agents and gloves work fine (i think so). However, there is an issue with not assigning knives and weapon skins

**Comment by t4r1k58** [comment]
please close this issue i solved clean setup
