### ISSUE TITLE
Build 224 error

### ISSUE THREAD

**Issue by Waterovsky** [Nereziel/cs2-WeaponPaints#207]
**CSS 193, meta 1284, WP 2.2d**
Skins work, but:

```
19:06:03 [EROR] (cssharp:Core) Error invoking callback

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'id')

   at CounterStrikeSharp.API.Modules.Entities.SteamID..ctor(UInt64 id) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Entities/SteamID.cs:line 13

   at CounterStrikeSharp.API.Utilities.<>c__DisplayClass10_0.<GetPlayerFromSteamId>b__0(CCSPlayerController player) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Utilities.cs:line 72

   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)

   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)

   at CounterStrikeSharp.API.Utilities.GetPlayerFromSteamId(UInt64 steamId) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Utilities.cs:line 72

   at WeaponPaints.WeaponPaints.<>c__DisplayClass14_0.<OnEntityCreated>b__0() in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/Events.cs:line 269

   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)

   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

   --- End of inner exception stack trace ---

   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at System.Delegate.DynamicInvokeImpl(Object[] args)

   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 120

```

**Comment by drakin003** [comment]
maybe its due to some other plugin? because I'm using same version and i get no errors

**Comment by gabrielsdelima75** [comment]
no errors on META 1282 + CSS 187

**Comment by asdfxD** [comment]
> maybe its due to some other plugin?

No, only C# and ws

C#193 / MetaMod 1284 ERRORS
C#193 / MetaMod 1282 ERRORS

![no](https://github.com/Nereziel/cs2-WeaponPaints/assets/24253340/553cc2e7-3a1d-4399-bbae-cee502c3249a)

**Comment by Waterovsky** [comment]
I tested it on test server. The error occurs only when bots are enabled. The `-nobots` parameter resolves the issue.
