### ISSUE TITLE
New Build 227 Error

### ISSUE THREAD

**Issue by xshadowbringer** [Nereziel/cs2-WeaponPaints#212]
```
18:06:39 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'id')
   at CounterStrikeSharp.API.Modules.Entities.SteamID..ctor(UInt64 id) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Entities/SteamID.cs:line 13
   at CounterStrikeSharp.API.Modules.Entities.SteamID.op_Explicit(UInt64 u) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Entities/SteamID.cs:line 19
   at WeaponPaints.WeaponPaints.<>c__DisplayClass14_0.<OnEntityCreated>b__0() in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/Events.cs:line 262
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 120
```

**Comment by criskkky** [comment]
Similar for me, but at disconnect

```
SV:  Disconnect client 'crisky' from server(2): NETWORK_DISCONNECT_DISCONNECT_BY_USER
"crisky<0><[U:1:10876629]><TERRORIST>" ChangeTeam() CTMDBG , team 2, req team 0 willSwitch 0, 698.91 
Client 0 'crisky' signon state SIGNONSTATE_FULL -> SIGNONSTATE_NONE
SV:  Dropped client 'crisky' from server(2): NETWORK_DISCONNECT_DISCONNECT_BY_USER
21:46:52 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'id')
   at CounterStrikeSharp.API.Modules.Entities.SteamID..ctor(UInt64 id) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Entities/SteamID.cs:line 13
   at CounterStrikeSharp.API.Modules.Entities.SteamID.op_Explicit(UInt64 u) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Entities/SteamID.cs:line 19
   at CounterStrikeSharp.API.Utilities.<>c__DisplayClass10_0.<GetPlayerFromSteamId>b__0(CCSPlayerController player) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Utilities.cs:line 72
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at CounterStrikeSharp.API.Utilities.GetPlayerFromSteamId(UInt64 steamId) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Utilities.cs:line 72
   at WeaponPaints.WeaponPaints.<>c__DisplayClass14_0.<OnEntityCreated>b__0() in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/Events.cs:line 269
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 120
   ```
