### ISSUE TITLE
[BUG] New update error

### ISSUE THREAD

**Issue by DeadPoolCS2** [Nereziel/cs2-WeaponPaints#250]
Hello,

After the new cs2 update plugin wont start anymore. 

2024-04-26 05:07:25.716 +03:00 [INFO] (cssharp:PluginContext) Loading plugin WeaponPaints
2024-04-26 05:07:25.856 +03:00 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/container/game/csgo/addons/counterstrikesharp/plugins/WeaponPaints/WeaponPaints.dll
CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176
   at CounterStrikeSharp.API.Core.NativeAPI.HookFunction(IntPtr function, InputArgument hook, Boolean post) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1033
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.BaseMemoryFunction.Hook(Func`2 handler, HookMode mode) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/BaseMemoryFunction.cs:line 62
   at WeaponPaints.WeaponPaints.RegisterListeners() in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/Events.cs:line 345
   at WeaponPaints.WeaponPaints.Load(Boolean hotReload) in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponPaints.cs:line 246
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93

**Comment by CreedoW** [comment]
I've tried to create a server yesterday and that stuff happened to me too, tried downgrading and now I'm on last version with same error.

`12:01:48 [INFO] (cssharp:Core) CounterStrikeSharp is starting up...
12:01:48 [INFO] (cssharp:CoreConfig) Successfully loaded core configuration
12:01:48 [INFO] (cssharp:GameDataProvider) Successfully loaded 33 game data entries from /serverz/cs2/game/csgo/addons/counterstrikesharp/gamedata/gamedata.json
12:01:48 [INFO] (cssharp:Core) Loading Admins from /serverz/cs2/game/csgo/addons/counterstrikesharp/configs/admins.json
12:01:48 [WARN] (cssharp:AdminManager) Admin data file not found. Skipping admin data load.
12:01:48 [INFO] (cssharp:Core) Loading Admin Groups from /serverz/cs2/game/csgo/addons/counterstrikesharp/configs/admin_groups.json
Admin groups file not found. Skipping admin groups load.
12:01:48 [INFO] (cssharp:Core) Loading Admin Command Overrides from /serverz/cs2/game/csgo/addons/counterstrikesharp/configs/admin_overrides.json
Admin command overrides file not found. Skipping admin command overrides load.
12:01:49 [INFO] (cssharp:PluginContext) Loading plugin WeaponPaints
12:01:49 [EROR] (cssharp:PluginManager) Failed to load plugin from /serverz/cs2/game/csgo/addons/counterstrikesharp/plugins/WeaponPaints/WeaponPaints.dll
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'WeaponPaints.WeaponPaints' threw an exception.
 ---> System.ArgumentException: Method CAttributeList_SetOrAddAttributeValueByName not found in gamedata.json
   at CounterStrikeSharp.API.Core.GameData.GetSignature(String key) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/GameData.cs:line 94
   at WeaponPaints.WeaponPaints..cctor() in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponPaints.cs:line 97
   --- End of inner exception stack trace ---
   at WeaponPaints.WeaponPaints.OnConfigParsed(WeaponPaintsConfig config) in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponPaints.cs:line 271
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at CounterStrikeSharp.API.Core.BasePlugin.InitializeConfig(Object instance, Type pluginType) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 392
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 217
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93`
   
   Ubuntu 20.04 LTS, latest steamcmd.

**Comment by mayersgamer** [comment]
use older plugin it works

**Comment by CreedoW** [comment]
Reinstalled the whole server, added everything back and its working decently
