### ISSUE TITLE
No knife is given

### ISSUE THREAD

**Issue by lostsoul6** [Nereziel/cs2-WeaponPaints#251]
Hi  , after today's game update , I noticed knives are not given . I updated css to latest version but still knives are not given . No player on the server has knife . they have pistol and guns and knives are removed . can you please check ?

**Comment by asdfxD** [comment]
same here, !ws, !kill, !wp aren't working. i can choose knives, but they only work on new round start

errors:

15:43:37 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176
   at CounterStrikeSharp.API.Core.NativeAPI.ExecuteVirtualFunction[T](IntPtr function, Object[] arguments) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1059
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.BaseMemoryFunction.InvokeInternal[T](Object[] args) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/BaseMemoryFunction.cs:line 72
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.MemoryFunctionWithReturn`7.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/MemoryFunctionWithReturn.cs:line 154
   at CounterStrikeSharp.API.Core.CCSPlayerController.GiveNamedItem(String item) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CCSPlayerController.cs:line 26
   at WeaponPaints.WeaponPaints.<>c__DisplayClass21_0.<RefreshWeapons>b__0() in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponAction.cs:line 169
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by lostsoul6** [comment]
@daffyyyy after updating to the latest WP version and latest css , I'm getting the following error : 

![update](https://github.com/Nereziel/cs2-WeaponPaints/assets/127633547/58f180cd-e376-4923-82d4-fe1eb80972cc)

**Comment by lostsoul6** [comment]
@asdfxD cs2 and also css have been updated today . perhaps those updates messed up WP plugin . need @daffyyyy to have a look but I think my error and your error is actually the same !

**Comment by brkvlr** [comment]
same problem css v217 and latest weaponpaints

**Comment by lostsoul6** [comment]
@daffyyyy the new update has not solved the error I sent in the screenshot above . using latest WP version and latest css version .
