### ISSUE TITLE
setting the knife model not working

### ISSUE THREAD

**Issue by dredek** [Nereziel/cs2-WeaponPaints#308]
Hi, after the last Valve update, I’m having trouble with setting the knife (!knife and www). From what I know, many others are experiencing the same issue. Even after changing the knife, the default skin remains.

`FollowCS2ServerGuidelines "false",`
CFG:
`{
  "Version": 6,
  "DatabaseHost": "xxx",
  "DatabasePort": 3306,
  "DatabaseUser": "xxx",
  "DatabasePassword": "xxx",
  "DatabaseName": "xxx",
  "CmdRefreshCooldownSeconds": 30,
  "Prefix": "[xxx]",
  "Website": "xxx",
  "Additional": {
    "KnifeEnabled": true,
    "GloveEnabled": true,
    "MusicEnabled": true,
    "AgentEnabled": true,
    "SkinEnabled": true,
    "CommandWpEnabled": true,
    "CommandKillEnabled": true,
    "CommandKnife": "knife",
    "CommandMusic": "mvp",
    "CommandGlove": "gloves",
    "CommandAgent": "agents",
    "CommandSkin": "ws",
    "CommandSkinSelection": "skins",
    "CommandRefresh": "wp",
    "CommandKill": "kill",
    "GiveRandomKnife": false,
    "GiveRandomSkin": false,
    "ShowSkinImage": true
  },
  "ConfigVersion": 6
}`

**Comment by XTREMAAAAA** [comment]
same problem
on my one server knives work correctly on the other they dont and configs is the same both times

icon of selected knife displays correctly but assigns
![213](https://github.com/user-attachments/assets/c27f31df-d67f-4e48-98d1-b268b0a96268)
 default knife

**Comment by romerocox** [comment]
I'm facing the same problem, on console I see:

```
23:13:24 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 187
at CounterStrikeSharp.API.Core.NativeAPI.ExecuteVirtualFunction[T](IntPtr function, Object[] arguments) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1103
at CounterStrikeSharp.API.Modules.Memory.VirtualFunction.<>c__DisplayClass28_0`3.<Create>b__1(TArg1 arg1, TArg2 arg2) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/VirtualFunctionSignature.cs:line 121
at WeaponPaints.WeaponPaints.SubclassChange(CBasePlayerWeapon weapon, UInt16 itemD) in C:\Users\Romero\Documents\WP-OFC\WeaponAction.cs:line 331
at WeaponPaints.WeaponPaints.GivePlayerWeaponSkin(CCSPlayerController player, CBasePlayerWeapon weapon) in C:\Users\Romero\Documents\WP-OFC\WeaponAction.cs:line 31
at WeaponPaints.WeaponPaints.GiveOnItemPickup(CCSPlayerController player) in C:\Users\Romero\Documents\WP-OFC\WeaponAction.cs:line 405
at WeaponPaints.WeaponPaints.OnItemPickup(EventItemPickup event, GameEventInfo _) in C:\Users\Romero\Documents\WP-OFC\Events.cs:line 229
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
--- End of inner exception stack trace ---
at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Delegate.DynamicInvokeImpl(Object[] args)
at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
23:13:24 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 187
at CounterStrikeSharp.API.Core.NativeAPI.ExecuteVirtualFunction[T](IntPtr function, Object[] arguments) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1103
at CounterStrikeSharp.API.Modules.Memory.VirtualFunction.<>c__DisplayClass28_0`3.<Create>b__1(TArg1 arg1, TArg2 arg2) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/VirtualFunctionSignature.cs:line 121
at WeaponPaints.WeaponPaints.SubclassChange(CBasePlayerWeapon weapon, UInt16 itemD) in C:\Users\Romero\Documents\WP-OFC\WeaponAction.cs:line 331
at WeaponPaints.WeaponPaints.GivePlayerWeaponSkin(CCSPlayerController player, CBasePlayerWeapon weapon) in C:\Users\Romero\Documents\WP-OFC\WeaponAction.cs:line 31
at WeaponPaints.WeaponPaints.GiveOnItemPickup(CCSPlayerController player) in C:\Users\Romero\Documents\WP-OFC\WeaponAction.cs:line 405
at WeaponPaints.WeaponPaints.OnItemPickup(EventItemPickup event, GameEventInfo _) in C:\Users\Romero\Documents\WP-OFC\Events.cs:line 229
at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of inner exception stack trace ---
```

Any thoughts?

**Comment by romerocox** [comment]
@dredek were you able to figure this out?

**Comment by romerocox** [comment]
@daffyyyy we're looking forward to hearing from you. We appreciate you
