### ISSUE TITLE
The given key 'menu:nfcore' was not present in the dictionary.

### ISSUE THREAD

**Issue by yichen11818** [Nereziel/cs2-WeaponPaints#316]
2024-10-19 11:41:02.417 +08:00 [EROR] (cssharp:PluginManager) OnAllPluginsLoaded failed
System.Collections.Generic.KeyNotFoundException: The given key 'menu:nfcore' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at CounterStrikeSharp.API.Core.Capabilities.PluginCapability`1.Get() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Capabilities/PluginCapability.cs:line 17
   at WeaponPaints.WeaponPaints.OnAllPluginsLoaded(Boolean hotReload) in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponPaints.cs:line 111
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 106

**Comment by yichen11818** [comment]
build-314

**Comment by yichen11818** [comment]
This issue was resolved; I didn't have the following installed:
[PlayerSettings](https://github.com/NickFox007/PlayerSettingsCS2) - Required by MenuManagerCS2
[AnyBaseLibCS2](https://github.com/NickFox007/AnyBaseLibCS2) - Required by PlayerSettings
[MenuManagerCS2](https://github.com/NickFox007/MenuManagerCS2)
