### ISSUE TITLE
Plugin failed to load with Build 344

### ISSUE THREAD

**Issue by ajaekel49** [Nereziel/cs2-WeaponPaints#340]
The following error appears after I updated the plugin to build 344. Database credentials are set in file:'
configs/plugins/WeaponPaints/WeaponPaints.json and mysql-server is running and accessable. Plugin worked before the update:

`13:48:53 [INFO] (cssharp:PluginContext) Loading plugin WeaponPaints
13:48:53 [EROR] (cssharp:ConfigManager) Failed to parse configuration file for WeaponPaints
System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.List`1[System.String]. Path: $.Additional.CommandKnife | LineNumber: 19 | BytePositionInLine: 27.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at CounterStrikeSharp.API.Modules.Config.ConfigManager.Load[T](String pluginName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Config/ConfigManager.cs:line 86
13:48:53 [EROR] (plugin:WeaponPaints) You need to setup Database credentials in "configs/plugins/WeaponPaints/WeaponPaints.json"!`

**Comment by Oneycs** [comment]
/csgo/addons/counterstrikesharp/plugins/configs/WeaponPaints

**Comment by Oneycs** [comment]
I didnt read your text, it seems that you have entered something wrong in the config. could you send me your config? (without db credentials)

**Comment by ajaekel49** [comment]
[WeaponPaints.json](https://github.com/user-attachments/files/17491665/WeaponPaints.json)

**Comment by ajaekel49** [comment]
@Oneycs : sorry - I wrote wrong build - it is not build 314 - its 344.
Corrected headline.

**Comment by Oneycs** [comment]
Then you need to generate a new config. U have a old config.

**Comment by Oneycs** [comment]
Just rename WeaponPaints.json to save.json or whatever you want (if you want to save the Config for the future). Or just delete it and after restart a new will create. Add your credentials and your good to go.

**Comment by ajaekel49** [comment]
Hey,
sorry - missed to confirm, that deleting this file worked as a charm.
Thanks for your  support!
