### ISSUE TITLE
Problem with gloves in use

### ISSUE THREAD

**Issue by PyPKjE** [Nereziel/cs2-WeaponPaints#353]
I discovered a problem with gloves that gloves does not load from the mysql database and does not put the weapon skin on the spawn or after using the !wp command

**Comment by Oneycs** [comment]
When you equip the gloves or do !ws does the console give any errors?

**Comment by PyPKjE** [comment]
There is no error log, and I would also like to add that using the !gloves command
command and glove skins are put on, mysql updates the data, but if the map changes, you have to put the gloves back on with !gloves

**Comment by Oneycs** [comment]
What version are you on?

**Comment by PyPKjE** [comment]
> There is no error log, and I would also like to add that using the !gloves command command and glove skins are put on, mysql updates the data, but if the map changes, you have to put the gloves back on with !gloves

@Oneycs I'm sorry, but I've found a mistake, maybe it's her?
`[EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponPaints.WeaponPaints.OnEntityCreated(CEntityInstance entity) in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/Events.cs:line 220
   at InvokeStub_OnEntityCreated.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass51_0`1.<RegisterListener>b__2(ScriptContext context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 298
   at InvokeStub_Action`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context)
`

**Comment by PyPKjE** [comment]
> What version are you on?

I use the latest versions of **WeaponPaint** and **CSSharp**

**Comment by PyPKjE** [comment]
![image](https://github.com/user-attachments/assets/b3445c60-1927-4ac1-b9b2-d96529d194fa)
I noticed where the glove skin ends
`HasChangedPaint(player, gloveId, out var weaponInfo)`
error in this function fails to process the glove-on system

**Comment by PyPKjE** [comment]
![image](https://github.com/user-attachments/assets/23e27229-2fe8-46aa-863a-3b9d5db46569)
I managed to get the glove overlay pattern by modifying the function, the only thing left to do is to make sure that the selected glove paint (skinid) is overlaid, but here I'll need to modify the mysql database in order to store the following information and to read it and load the following data

**Comment by daffyyyy** [comment]
> ![image](https://github.com/user-attachments/assets/b3445c60-1927-4ac1-b9b2-d96529d194fa)
> I noticed where the glove skin ends
> `HasChangedPaint(player, gloveId, out var weaponInfo)`
> error in this function fails to process the glove-on system

Its not from pure WeaponPaints, please use version from this repo.
