### ISSUE TITLE
Failed to load after lastest game update

### ISSUE THREAD

**Issue by RafaelMRG** [Nereziel/cs2-WeaponPaints#367]
After today's update (version 1.40.5.7), plugin stopped working giving this stack trace:

```
23:51:54 [INFO] (plugin:WeaponPaints) Plugin is up to date
Dec 19 23:51:54:  23:51:54 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/dathost/cs2_linux/game/csgo/addons/counterstrikesharp/plugins/WeaponPaints/WeaponPaints.dll
Dec 19 23:51:54:  CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
Dec 19 23:51:54:     at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 187
Dec 19 23:51:54:     at CounterStrikeSharp.API.Core.NativeAPI.HookFunction(IntPtr function, InputArgument hook, Boolean post) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1087
Dec 19 23:51:54:     at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.BaseMemoryFunction.Hook(Func`2 handler, HookMode mode) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/BaseMemoryFunction.cs:line 62
Dec 19 23:51:54:     at WeaponPaints.WeaponPaints.RegisterListeners() in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/Events.cs:line 346
Dec 19 23:51:54:     at WeaponPaints.WeaponPaints.Load(Boolean hotReload) in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponPaints.cs:line 65
Dec 19 23:51:54:     at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
Dec 19 23:51:54:     at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
Dec 19 23:51:54:     at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93
```

**Comment by daffyyyy** [comment]
Update CSS & meta
