### ISSUE TITLE
Error:Cant load plugins.User can use skins but cant use commands like !wp and !gloves

### ISSUE THREAD

**Issue by Swhite429** [Nereziel/cs2-WeaponPaints#370]
03:02:25 [INFO] (plugin:WeaponPaints) Plugin is up to date
[Info] - Trampoline - Bounds of relative addresses accessed [FFFFFFFFFFFFFFFF, 0000000000000000]
[Info] - Trampoline - Attempting to allocate trampoline within +-2GB range of 00007FF8DD3D1520
[Info] - Trampoline - Allocated trampoline at 00007FF95D3D0000 (using 1 attempts)
03:02:25 [INFO] (cssharp:PluginContext) Finished loading plugin WeaponPaints
03:02:25 [EROR] (plugin:WeaponPaints) Error while loading required plugins
Could not load plugin "D:\steamcmd\steamapps\common\Counter-Strike Global Offensive\game\csgo\addons\counterstrikesharp\plugins/WeaponPaints/WeaponPaints.dll"
03:02:25 [EROR] (cssharp:Core) Could not load plugin "D:\steamcmd\steamapps\common\Counter-Strike Global Offensive\game\csgo\addons\counterstrikesharp\plugins/WeaponPaints/WeaponPaints.dll"
System.Collections.Generic.KeyNotFoundException: The given key 'menu:nfcore' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at CounterStrikeSharp.API.Core.Capabilities.PluginCapability`1.Get() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Capabilities/PluginCapability.cs:line 17
   at WeaponPaints.WeaponPaints.OnAllPluginsLoaded(Boolean hotReload) in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponPaints.cs:line 112
   at CounterStrikeSharp.API.Core.Application.OnCSSPluginCommand(CCSPlayerController caller, CommandInfo info) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Application.cs:line 172

**Comment by mrc4tt** [comment]
You didn't install the required plugins... :-)

**Comment by Swhite429** [comment]
Yes.its working now .i mistake to delete MenuMannagerCS2 thx for your fast reply :-)
