### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by dendecsro** [Nereziel/cs2-WeaponPaints#372]
I run my cs2 server on debian linux with

CounterStrikeSharp v296 and Metamod:Source version 2.0.0-dev+1314

In logs I get this message 

2024-12-27 03:21:38.250 -05:00 [EROR] plugin:WeaponPaints Error while loading required plugins
2024-12-27 03:21:38.250 -05:00 [EROR] (cssharp:PluginManager) OnAllPluginsLoaded failed
System.Collections.Generic.KeyNotFoundException: The given key 'menu:nfcore' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at CounterStrikeSharp.API.Core.Capabilities.PluginCapability`1.Get() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Capabilities/PluginCapability.cs:line 17
   at WeaponPaints.WeaponPaints.OnAllPluginsLoaded(Boolean hotReload) in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponPaints.cs:line 112
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 106

and plugin refuses to load, I followed all the steps already, I added weaponpaints.json to addons/counterstrikesharp/gamedata/

Please advise. Thank you!

**Comment by mrc4tt** [comment]
Did you read https://github.com/Nereziel/cs2-WeaponPaints/blob/main/README.md ?

It says you NEED to install these 3 plugins:
- [PlayerSettings](https://github.com/NickFox007/PlayerSettingsCS2) - Required by MenuManagerCS2
- [AnyBaseLibCS2](https://github.com/NickFox007/AnyBaseLibCS2) - Required by PlayerSettings
- [MenuManagerCS2](https://github.com/NickFox007/MenuManagerCS2)

**Comment by dendecsro** [comment]
Is fixed now, thank you
