### ISSUE TITLE
plugin wont load at all

### ISSUE THREAD

**Issue by chicken-cs** [Nereziel/cs2-WeaponPaints#374]
I installed and followed the instructions for database and files

 04:55:52 [EROR] (cssharp:PluginManager) OnAllPluginsLoaded failed
Dec 30 04:55:52:  System.TypeInitializationException: The type initializer for 'WeaponPaints.WeaponPaints' threw an exception.
Dec 30 04:55:52:   ---> System.ArgumentException: Method CAttributeList_SetOrAddAttributeValueByName not found in gamedata.json
Dec 30 04:55:52:     at CounterStrikeSharp.API.Core.GameData.GetSignature(String key) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/GameData.cs:line 94
Dec 30 04:55:52:     at WeaponPaints.WeaponPaints..cctor() in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/Variables.cs:line 94
Dec 30 04:55:52:     --- End of inner exception stack trace ---
Dec 30 04:55:52:     at WeaponPaints.WeaponPaints.OnAllPluginsLoaded(Boolean hotReload) in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponPaints.cs:line 131
Dec 30 04:55:52:     at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 106
Dec 30 04:55:52:  [04:55:52.872] CSSharp: CounterStrikeSharp.API Loaded Successfully.
Dec 30 04:55:52:  [04:55:52.874] CSSharp: Initialized GameSystem.
Dec 30 04:55:52:  [04:55:52.874] CSSharp: Hooks added.

That might not be the error but everything should be installed correctly

**Comment by mrc4tt** [comment]
Seems you didnt follow the guide..

**Comment by andersontvcs2** [comment]
> Seems you didnt follow the guide..

Really Helpful reply!

**Comment by mrc4tt** [comment]
> Really Helpful reply!

Of course, you didn't read readme did you?

**Copy from weaponpaints's folder gamedata file weaponpaints.json to folder addons/counterstrikesharp/gamedata/**
