### ISSUE TITLE
Weapon Paints dont apply

### ISSUE THREAD

**Issue by audiomaster99** [Nereziel/cs2-WeaponPaints#39]
Hey guys, im having some issues, and could not figure out what was the problem. So..

Knifes apply when you change them, but you have to reconnect.
Weapon paints do not apply not eaven after reconnect. Data base is writing all data put it dosent get applyd in game. Try'd !wp reconnecting, restarting server.

Using latest dev build of meta mod, tried CSS from v50 to v54, and WeaponPaints Build 43 and 46.

```
CounterStrikeSharp.API.Core.NativeException: Could not find signature
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 178
```
```
System.Collections.Generic.KeyNotFoundException: The given key 'weapon_defindex' was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException[T](T key)
The given key 'weapon_defindex' was not present in the dictionary.
```
Im finding these 2 "errors" in console...

**Comment by daffyyyy** [comment]
Wait for #40

**Comment by audiomaster99** [comment]
> Wait for #40

Its kinda weird cuz, i got it working on 2 servers, but tried other 2 it dosent work, same everything css/meta/plugin ver/database. On one it only saves knife, on the other nothing

```
System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
```

**Comment by audiomaster99** [comment]
> Wait for #40

Updated to css v56, and latest build, tryd on old database didnt work, made a new one, this is what I get. (idk what im doing wrong)

```
MySqlConnector.MySqlException (0x80004005): Table 's442_brws.wp_player_skins' doesn't exist
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 936
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 37
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
   at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 483
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 357
   at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 350
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 434
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Table 's442_brws.wp_player_skins' doesn't exist
```

**Comment by daffyyyy** [comment]
> > Wait for #40
> 
> Updated to css v56, and latest build, tryd on old database didnt work, made a new one, this is what I get. (idk what im doing wrong)
> 
> ```
> MySqlConnector.MySqlException (0x80004005): Table 's442_brws.wp_player_skins' doesn't exist
>    at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 936
>    at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 37
>    at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
>    at MySqlConnector.MySqlDataReader.InitAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 483
>    at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
>    at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 357
>    at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 350
>    at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 434
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> Table 's442_brws.wp_player_skins' doesn't exist
> ```

Restarted server after new database created?

**Comment by daffyyyy** [comment]
Wait for new release or create database tables manually at the moment

```
CREATE TABLE `wp_player_skins` (
  `steamid` varchar(64) NOT NULL,
  `weapon_defindex` int(6) NOT NULL,
  `weapon_paint_id` int(6) NOT NULL,
  `weapon_wear` float NOT NULL DEFAULT 0.0001,
  `weapon_seed` int(16) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

CREATE TABLE `wp_player_knife` (
  `steamid` varchar(64) NOT NULL,
  `knife` varchar(64) NOT NULL,
  UNIQUE (`steamid`)
) ENGINE = InnoDB;
```

#42  should fix problem

**Comment by audiomaster99** [comment]
> Wait for new release or create database tables manually at the moment
> 
> ```
> CREATE TABLE `wp_player_skins` (
>   `steamid` varchar(64) NOT NULL,
>   `weapon_defindex` int(6) NOT NULL,
>   `weapon_paint_id` int(6) NOT NULL,
>   `weapon_wear` float NOT NULL DEFAULT 0.0001,
>   `weapon_seed` int(16) NOT NULL DEFAULT 0
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;
> 
> CREATE TABLE `wp_player_knife` (
>   `steamid` varchar(64) NOT NULL,
>   `knife` varchar(64) NOT NULL,
>   UNIQUE (`steamid`)
> ) ENGINE = InnoDB;
> ```
> 
> #42 should fix problem

for some weird reason map has to be changed for skins to work
