### ISSUE TITLE
[BUG] Plugin cant load

### ISSUE THREAD

**Issue by himenekocn** [Nereziel/cs2-WeaponPaints#41]
only test on windows server
CSS version v56 
Plugin version 49
Log : 
```
Failed to load plugin D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\game\csgo\addons\counterstrikesharp\plugins\WeaponPaints\WeaponPaints.dll with error System.Exception: Unknown mysql exception! Connection is not open.
   at WeaponPaints.WeaponPaints.CheckDatabaseTables() in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponPaints.cs:line 157
   at WeaponPaints.WeaponPaints.TestDatabaseConnection() in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponPaints.cs:line 127
   at WeaponPaints.WeaponPaints.Load(Boolean hotReload) in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponPaints.cs:line 72
   at CounterStrikeSharp.API.Core.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/PluginContext.cs:line 108
   at CounterStrikeSharp.API.Core.GlobalContext.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/GlobalContext.cs:line 97
   at CounterStrikeSharp.API.Core.GlobalContext.LoadAllPlugins() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/GlobalContext.cs:line 136
```

**Comment by daffyyyy** [comment]
As exception said
`Unknown mysql exception! Connection is not open.`
Something wrong with conenction to database

**Comment by himenekocn** [comment]
> As exception said Something wrong with conenction to database credentials or host issue`Unknown mysql exception! Connection is not open.`

but old version can connect mysql

**Comment by daffyyyy** [comment]
wait for #42, maybe help
