### ISSUE TITLE
Failed to load plugin 

### ISSUE THREAD

**Issue by morkvk** [Nereziel/cs2-WeaponPaints#43]
Loading plugin: WeaponPaints
Failed to load plugin C:\SERVER\cs2_server\cs2_kotlet\game\csgo\addons\counterstrikesharp\plugins\WeaponPaints\WeaponPaints.dll with error System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: You need to setup Database credentials in config!
   at WeaponPaints.WeaponPaints.OnConfigParsed(WeaponPaintsConfig config) in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponPaints.cs:line 91
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at CounterStrikeSharp.API.Core.BasePlugin.InitializeConfig(Object instance, Type pluginType) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 354
   at CounterStrikeSharp.API.Core.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/PluginContext.cs:line 107
   at CounterStrikeSharp.API.Core.GlobalContext.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/GlobalContext.cs:line 97
   at CounterStrikeSharp.API.Core.GlobalContext.LoadAllPlugins() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/GlobalContext.cs:line 136

**Comment by daffyyyy** [comment]
Exception message solved problem :D 
Check config

**Comment by Nereziel** [comment]
You need to setup Database credentials in config!

**Comment by morkvk** [comment]
lol so the config is not created what are you talking about

**Comment by morkvk** [comment]
the message does not solve the problem, it says that you need to enter data into the config. the config is not being created due to an error
