### ISSUE TITLE
[BUG] Crash on load with GlobalShare enabled

### ISSUE THREAD

**Issue by dogoterra** [Nereziel/cs2-WeaponPaints#77]
I get this error when activating GlobalShare option:

> 2023-11-30 12:56:17.739 +00:00 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/dathost/cs2_linux/game/csgo/addons/counterstrikesharp/plugins/WeaponPaints/WeaponPaints.dll
System.FormatException: The input string '' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Int32.Parse(String s)
   at WeaponPaints.WeaponPaints.GlobalShareConnect() in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponPaints.cs:line 195
   at WeaponPaints.WeaponPaints.Load(Boolean hotReload) in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponPaints.cs:line 105
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 182
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 52
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 34

**Comment by daffyyyy** [comment]
Its exception not crash :P 
Wait for #78
