### ISSUE TITLE
Console logs

### ISSUE THREAD

**Issue by skaen** [Nereziel/cs2-WeaponPaints#87]
CSS API Version: 98

```[39;49m[37m16:47:14[39;49m[39;49m[30m [[39;49m[39;49m[37m[39;49m[37m[41mEROR[39;49m[39;49m[30m] (cssharp:[39;49m[39;49m[37mCore[39;49m[39;49m[30m) [39;49m[39;49m[37mError invoking callback[39;49m
[39;49m[37mSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.[39;49m
[39;49m[37m ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.[39;49m
[39;49m[37m   at System.Runtime.InteropServices.Marshal.ReadInt64(IntPtr ptr, Int32 ofs)[39;49m
[39;49m[37m   at CounterStrikeSharp.API.Core.CBasePlayerPawn.get_WeaponServices() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Objects.g.cs:line 4757[39;49m
[39;49m[37m   at WeaponPaints.WeaponPaints.PlayerHasKnife(CCSPlayerController player) in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/WeaponAction.cs:line 89[39;49m
[39;49m[37m   at WeaponPaints.WeaponPaints.OnPlayerSpawn(EventPlayerSpawn event, GameEventInfo info) in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/Events.cs:line 162[39;49m
[39;49m[37m   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)[39;49m
[39;49m[37m   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)[39;49m
[39;49m[37m   --- End of inner exception stack trace ---[39;49m
[39;49m[37m   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)[39;49m
[39;49m[37m   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)[39;49m
[39;49m[37m   at System.Delegate.DynamicInvokeImpl(Object[] args)[39;49m
[39;49m[37m   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82[39;49m```

**Comment by skaen** [comment]
```
[39;49m[37m13:41:41[39;49m[39;49m[30m [[39;49m[39;49m[37m[39;49m[37m[41mEROR[39;49m[39;49m[30m] (cssharp:[39;49m[39;49m[37mCore[39;49m[39;49m[30m) [39;49m[39;49m[37mError invoking callback[39;49m
[39;49m[37mSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.[39;49m
[39;49m[37m ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.[39;49m
[39;49m[37m   at WeaponPaints.WeaponPaints.<>c__DisplayClass3_0.<SetupKnifeMenu>b__4(CCSPlayerController player, CommandInfo info) in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/Commands.cs:line 163[39;49m
[39;49m[37m   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass37_0.<AddCommand>b__0(Int32 i, IntPtr ptr) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 234[39;49m
[39;49m[37m   at InvokeStub_Action`2.Invoke(Object, Object, IntPtr*)[39;49m
[39;49m[37m   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)[39;49m
[39;49m[37m   --- End of inner exception stack trace ---[39;49m
[39;49m[37m   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)[39;49m
[39;49m[37m   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)[39;49m
[39;49m[37m   at System.Delegate.DynamicInvokeImpl(Object[] args)[39;49m
[39;49m[37m   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82[39;49m
```

**Comment by DOK-26-RUS** [comment]
`2023-12-08 23:03:05.466 +03:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at WeaponPaints.WeaponPaints.OnEntitySpawned(CEntityInstance entity) in /home/runner/work/cs2-WeaponPaints/cs2-WeaponPaints/Events.cs:line 52
   at InvokeStub_OnEntitySpawned.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass41_0`1.<RegisterListener>b__2(ScriptContext context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 332
   at InvokeStub_Action`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82`

**Comment by Nereziel** [comment]
Do you have still problems?

**Comment by DOK-26-RUS** [comment]
No, it's okay.
